/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import javax.swing.table.DefaultTableModel;
import datos.Usuario;
import gui.tablemodels.UsuariosTableModel;
import java.util.List;
import logica.logicaUsuarios;

/**
 *
 * @author solet
 */
public class PantallaPerfil extends javax.swing.JDialog {
    
    /**
     * Creates new form PantallaPerfil
     */
    public PantallaPerfil(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        refrescarTabla();
    }
    
    public PantallaPerfil(){
        initComponents();
        refrescarTabla();
    }
    private void refrescarTabla(){
        DefaultTableModel dtm = new DefaultTableModel();
        //UsuariosTableModel utm = new UsuariosTableModel(logicaUsuarios.getListaUsuarios());
        dtm.setColumnIdentifiers(new String[]{"Nombre", "Apellidos", "Provincia", "Fecha Nacimiento"});
        List<Usuario> listaUsuarios = logicaUsuarios.getListaUsuarios();
        for (Usuario usuario : listaUsuarios){
           dtm.addRow(usuario.toArrayString());
       }
//        for (Usuario usuario : listaUsuarios){
//            utm.addRow(usuario.toArrayString());
//        }
        jTablePerfiles.setModel(dtm);
        //jTablePerfiles.setModel(new UsuariosTableModel(logicaUsuarios.getListaUsuarios()));
    }
//    public void aniadirPerfil(Usuario usuario){
//        DefaultTableModel dtm = (DefaultTableModel)jTablePerfiles.getModel();
//        dtm.addRow(usuario.toArrayString());
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePerfiles = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPerfil = new javax.swing.JMenu();
        jMenuItemEditarPerfil = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTablePerfiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePerfiles);

        jMenuPerfil.setText("Tu perfil");

        jMenuItemEditarPerfil.setText("Crear nuevo perfil");
        jMenuItemEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarPerfilActionPerformed(evt);
            }
        });
        jMenuPerfil.add(jMenuItemEditarPerfil);

        jMenuBar1.add(jMenuPerfil);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarPerfilActionPerformed
        //PantallaRegistro pantallaRegistro = new PantallaRegistro(PantallaRegistro, true);
        //pantallaRegistro.setVisible(true);
        //refrescarTabla();
    }//GEN-LAST:event_jMenuItemEditarPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PantallaPerfil dialog = new PantallaPerfil(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemEditarPerfil;
    private javax.swing.JMenu jMenuPerfil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePerfiles;
    // End of variables declaration//GEN-END:variables
}
